Feature 144 cleaning forecast
Metatavu/home-lambdas pull request #145
Opened 2024-12-13 07:45 UTC by McDuuck

2024-12-13 09:06 UTC, Hanhz2707 commented on src/functions/memo-management/drive-memos/get-content-pdf/handler.ts
>  } from "aws-lambda";
```suggestion
import type {
  APIGatewayProxyEventV2,
  APIGatewayProxyStructuredResultV2,
  APIGatewayProxyHandlerV2,
} from "aws-lambda";
```

2024-12-13 09:09 UTC, Hanhz2707 commented on src/functions/memo-management/drive-memos/get-memos-pdf/handler.ts
>  import { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```suggestion
import type { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```

2024-12-13 09:11 UTC, Hanhz2707 commented on src/functions/memo-management/drive-memos/get-summary-memo-pdf/handler.ts
>  import { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```suggestion
import type { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```

2024-12-13 09:13 UTC, Hanhz2707 commented on src/functions/memo-management/drive-memos/get-translated-memo-pdf/handler.ts
>  import { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```suggestion
import type { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```

2024-12-13 09:14 UTC, Hanhz2707 commented on src/functions/memo-management/trello-cards/comment-trello-card/handler.ts
>  import { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```suggestion
import type { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```

2024-12-13 09:15 UTC, Hanhz2707 commented on src/functions/memo-management/trello-cards/create-trello-card/handler.ts
>  import { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```suggestion
import type { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```

2024-12-13 09:15 UTC, Hanhz2707 commented on src/functions/memo-management/trello-cards/delete-trello-card/handler.ts
>  import { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```suggestion
import type { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
```

2024-12-13 09:16 UTC, Hanhz2707 commented on src/functions/memo-management/trello-cards/get-board-members/handler.ts
>  import { APIGatewayProxyHandler } from "aws-lambda";
```suggestion
import type { APIGatewayProxyHandler } from "aws-lambda";
```

2024-12-13 09:17 UTC, Hanhz2707 commented on src/functions/memo-management/trello-cards/get-trello-cards/handler.ts
>  import { TrelloCardWithComments } from "src/schema/trello";
```suggestion
import type { APIGatewayProxyHandler } from "aws-lambda";
import type { TrelloCardWithComments } from "src/schema/trello";
```

2024-12-13 09:20 UTC, Hanhz2707 commented on src/functions/meta-assistant/send-daily-message/handler.ts
>  };
```suggestion
  }
};

/**
 * Lambda function for sending slack message
 *
 * @param event API Gateway proxy event
 * @returns JSON response
 */
```

2024-12-13 09:20 UTC, Hanhz2707 commented on src/functions/meta-assistant/send-daily-message/handler.ts
>  };
Maybe a empty line here would be better

2024-12-13 19:07 UTC, Hanhz2707 commented on src/meta-assistant/slack/slack-utils.ts
> +  * Find the corresponding Slack user
I think you forgot TS Docs for @params here

2024-12-13 19:08 UTC, Hanhz2707 commented on src/meta-assistant/slack/slack-utils.ts
> +  };
```suggestion
    }
  };
  
  /**
   * Create message based on specific users timebank data
   *
   * @param user severa data
   * @param numberOfToday Todays number
   * @returns string message if id match
   */
```

2024-12-13 19:08 UTC, Hanhz2707 commented on src/meta-assistant/slack/slack-utils.ts
> +  };
Empty line here should be ok

2024-12-13 19:12 UTC, Hanhz2707 commented on src/services/severa-api-service.ts
> +     *
```suggestion
    /**
     * Gets Workdays from Severa
     * 
     * @param severaUserId Severa user id
     * @returns Workdays of a user
     */
```

2024-12-13 19:12 UTC, Hanhz2707 commented on src/services/severa-api-service.ts
> +     *
Maybe we should remove this extra line too

2024-12-13 19:19 UTC, Hanhz2707 commented
Just small changes , the rest is ok

2024-12-13 19:19 UTC, Hanhz2707 approved these changes

2025-01-02 10:02 UTC, Jdallos requested changes
Searching Forecast in VSCode within the project will show there are more things to be removed including the time-bank-api-spec submodule which is no longer needed, the time-bank-api generated files, the references to the forecast envs, imports in src/functions, filter-utils in src/libs etc.

I'd say leave all tests/ mocks files as they are as they might be a useful reference for someone in the future if we decide to recreate tests for the MA.

Up to you if you want to leave the weekly-message handler to be fixed in the separate feature.

2025-01-02 13:29 UTC, Jdallos approved these changes

2025-01-02 13:29 UTC, Jdallos commented on src/functions/slack-user-avatar/handler.ts
> +    throw new Error("Severa authentication failed");
```suggestion
    throw new Error("User authentication failed");
```

2025-01-02 13:29 UTC, Jdallos commented on src/functions/slack-user-avatar/handler.ts
> -    }
Lets comment out this code (rather than delete) and leave a TODO: comment that it needs to be updated to use SeveraUsers. It might be a useful reference for whoever implements this feature in the future.

2025-01-02 13:29 UTC, Jdallos commented on src/functions/slack-user-avatar/handler.ts
> -    }
Lets comment out this code (rather than delete) and leave a TODO: comment that it needs to be updated to use SeveraUsers. It might be a useful reference for whoever implements this feature in the future.

2025-01-02 13:29 UTC, Jdallos commented on src/meta-assistant/auth/auth-provider.ts
> +   * Get severa access token from keycloak
```suggestion
   * Get access token from keycloak
```

2025-01-02 13:48 UTC, merged