made questionnaire service, model, renamed api to database, added cli…
Metatavu/home-lambdas pull request #61
Opened 2024-09-17 05:27 UTC by McDuuck

…ent folder and index.ts, added serverless resource and updated readme

2024-09-17 05:47 UTC, dalju005-xamk approved these changes

2024-09-17 05:47 UTC, dalju005-xamk commented on src/database/schemas/questionnaire/questionnaire.ts
> +  question: string;
Could this be question -> questionText, and in options value could be isCorrect ?
Do we need interface to passedUsers? Or could all that information be in one object ?
Could passScore be more like passingScore or minPassScore ?

2024-09-18 06:23 UTC, Jdallos requested changes

2024-09-18 06:23 UTC, Jdallos commented on serverless.ts
> +      QuestionnaireTable: {
```suggestion
      Questionnaires: {
```

2024-09-18 06:23 UTC, Jdallos commented on serverless.ts
> +          TableName: "questionnaire",
```suggestion
          TableName: "questionnaires",
```

2024-09-18 06:23 UTC, Jdallos commented on src/database/schemas/questionnaire/questionnaire.ts
> +export interface QuestionnaireModel {
Add Docs

2024-09-18 06:23 UTC, Jdallos commented on src/database/schemas/questionnaire/questionnaire.ts
> +export interface Question {
Add Docs

2024-09-18 06:23 UTC, Jdallos commented on src/database/schemas/questionnaire/questionnaire.ts
> +export interface Option {
Add Docs

2024-09-18 06:23 UTC, Jdallos commented on src/database/services/quiz-api-service.ts
> +const tableName = process.env.QUESTIONNAIRE_TABLE;
Looking at the elastic app functions I don't think the table name needs to be an env. Lets remove it as an env (as we name it in the serverless.ts anyway) and just add it here as a string

2024-09-18 06:23 UTC, Jdallos commented on src/database/services/quiz-api-service.ts
> +const tableName = process.env.QUESTIONNAIRE_TABLE;
Lets treat this as a const so rename TABLE_NAME

2024-09-18 07:04 UTC, Jdallos approved these changes

2024-09-18 07:04 UTC, Jdallos commented on src/database/schemas/questionnaire/questionnaire.ts
> +
```suggestion
```

2024-09-18 07:04 UTC, Jdallos commented on src/database/schemas/questionnaire/questionnaire.ts
> +
```suggestion
```

2024-09-18 07:04 UTC, Jdallos commented on src/database/schemas/questionnaire/questionnaire.ts
> +
```suggestion
```

2024-09-18 07:28 UTC, merged