Update lambda function
Metatavu/home-lambdas pull request #70
Opened 2024-09-23 06:48 UTC by McDuuck

2024-09-23 06:57 UTC, dalju005-xamk commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +import { ValidatedEventAPIGatewayProxyEvent } from "@libs/api-gateway";
Perhaps use type of here ?
```suggestion
import type { ValidatedEventAPIGatewayProxyEvent } from "@libs/api-gateway";
```

2024-09-23 06:59 UTC, dalju005-xamk commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +const updateQuestionnaire: ValidatedEventAPIGatewayProxyEvent<typeof QuestionnaireModel> = async event => {
Perhaps like this ?
```suggestion
const updateQuestionnaire: ValidatedEventAPIGatewayProxyEvent<typeof QuestionnaireModel> = async event => 
```

2024-09-23 07:01 UTC, dalju005-xamk commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +  const questionnaireUpdates: QuestionnaireModel = {
Make Import already. The model is now in develop.

```suggestion
  import type QuestionnaireModel from "src/database/models/questionnaire";
```

2024-09-23 07:02 UTC, dalju005-xamk commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +    const updatedQuestionnaire = await questionnaireService.updateQuestionnaire(questionnaireUpdates);
Import this also.

```suggestion
   import { questionnaireService } from "src/database/services";
```

2024-09-23 07:42 UTC, AfoninOleksandr approved these changes

2024-09-23 08:00 UTC, dalju005-xamk approved these changes

2024-09-25 06:08 UTC, Jdallos requested changes
Changes requested

2024-09-25 06:08 UTC, Jdallos commented on serverless.ts
This branch needs to be merged with the updated develop, you are missing updated table name in serverless.ts and fetch import for the keycloak service.
Also please check this is the serverless.ts:
AttributeDefinitions: [{ AttributeName: "id", AttributeType: "N" }],

I've just approved a spec change changing questionnaire id to be a string, so this may need updating

2024-09-25 06:08 UTC, Jdallos commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +const updateQuestionnaire: ValidatedEventAPIGatewayProxyEvent<typeof questionnaireSchema> = async event => {
Other functions are named createQuestionnaire**Handler** etc. Lets keep the naming consistent so lets rename this updateQuestionnaireHandler

2024-09-25 06:08 UTC, Jdallos commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +      body: "Bad request"
```suggestion
      body: "Bad request, missing id"
```

2024-09-25 06:08 UTC, Jdallos commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +  const { pathParameters, body, } = event;
```suggestion
  const { pathParameters, body } = event;
```

2024-09-25 06:08 UTC, Jdallos commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +  };
We should allocate to each attribute specifically here. The UI will fetch the existing questionnaire to be updated, the user will update the given fields, and then the whole questionnaire will be sent to the lambda as is. In this case probably only id needs to come from the existingQuestionnaire (although you have that from the lambda event as id also, i'd still use if from existingQuestionnaire).

Here is an example of what I mean from updateCurations:
  const curationUpdates: CurationModel = {
    id: existingCuration.id,
    name: name,
    elasticCurationId: existingCuration.elasticCurationId,
    documentId: existingCuration.documentId,
    queries: queries,
    promoted: curationType === CurationType.CUSTOM ? existingCuration.promoted : promoted,
    hidden: curationType === CurationType.CUSTOM ? existingCuration.hidden : hidden,
    startTime: startTime,
    endTime: endTime,
    curationType: curationType,
    groupId: groupId,
    language: language,
    invalidDocuments: invalidDocuments
  };
  
  In this case the attributes e.g. name, queries etc have already been destructured from the body, you should do similar

2024-09-26 06:45 UTC, Jdallos requested changes

2024-09-26 06:45 UTC, Jdallos commented on serverless.ts
It's still AttributeDefinitions: [{ AttributeName: "id", AttributeType: "N" }],


But I thought it should not be S as the spec was changed yesterday?

2024-09-26 06:45 UTC, Jdallos commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +    passScore: existingQuestionnaire.passScore,
The only thing that should be coming form the existing questionnaire is the id. All the other attributes should come from the body, otherwise we are not actually updating the questionnaire.
As mentioned in a comment previously I would suggest destructuring the properties from the event body at the start of the lambda once you have destructured the body from the event.

e.g.
  const { title, description, options, tags, passedUsers, passScore } = body;
  
  See the elastic update curations as a reference

2024-09-26 12:09 UTC, Jdallos approved these changes

2024-09-26 12:09 UTC, Jdallos commented on src/functions/questionnaire/update-questionnaire/handler.ts
> +
```suggestion
```

2024-09-26 12:21 UTC, merged