Feature 6 functionality implemented
Metatavu/home-lambdas pull request #8
Opened 2022-11-08 08:16 UTC by nojuord

2022-11-08 09:09 UTC, Jdallos reviewed
Some suggestions

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-projects/handler.ts
> +        if (project.end_date == null || new Date(parameters.endDate) >= new Date(project.end_date)) {
fix indentation

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-tasks/handler.ts
> +async function listTasksFunction(api: ForecastApiService, parameters: Parameters): Promise<Response[]> {
function comments

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-tasks/handler.ts
> +  if (parameters.projectId != null) {
```suggestion
  if (parameters.projectId !== null) {
```

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-tasks/handler.ts
> +    var filteredTasks = tasks.filter(task => task.project_id == parameters.projectId);
All var should be const, (unless they have to be let)

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-tasks/handler.ts
> +  const responseTasks = filteredTasks.map(task => {
can be implicit return

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-tasks/handler.ts
> +    var filteredTasks = tasks.filter(task => task.project_id == parameters.projectId);
```suggestion
    var filteredTasks = tasks.filter(task => task.project_id === parameters.projectId);
```

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-time-entries/handler.ts
> +interface Parameters {
add comments

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-time-entries/handler.ts
> +interface Response {
add comments

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-time-entries/handler.ts
> +async function listTimeEntriesFunction(api: ForecastApiService, parameters: Parameters): Promise<Response[]> {
add comments

2022-11-08 09:09 UTC, Jdallos commented on src/functions/list-time-entries/handler.ts
> +  const responseTimeEntries = timeEntries.map(timeEntry => {
implicit return

2022-11-08 12:10 UTC, Jdallos commented on src/functions/list-project-sprints/handler.ts
> +    projectId: parseInt(event.queryStringParameters.projectId),
```suggestion
    projectId: parseInt(event.queryStringParameters.projectId)
```

2022-11-08 12:10 UTC, Jdallos commented on src/functions/list-project-sprints/handler.ts
> +  return filteredSprints.map(sprint => {
I meant implicit return with ()

2022-11-10 08:47 UTC, anttileppa requested changes

2022-11-10 08:47 UTC, anttileppa commented on src/libs/filter-utils.ts
> +export const filterByDate = (object: { start_date: string, end_date: string }, currentDate: Date, parameters: { startDate?: Date, endDate?: Date }): boolean => {
This should be wrapped inside a namespace

2022-11-10 08:47 UTC, anttileppa commented on src/libs/filter-utils.ts
> +export const filterByDate = (object: { start_date: string, end_date: string }, currentDate: Date, parameters: { startDate?: Date, endDate?: Date }): boolean => {
Add documentations

2022-11-10 09:13 UTC, Jdallos commented on src/apis/forecast-api-service.ts
> +    const apiKey: string = process.env.FORECAST_API_KEY;
Task created:

2022-11-10 09:27 UTC, Jdallos commented on src/apis/forecast-api-service.ts
> +export interface ForecastApiService {
Task created:
https://github.com/Metatavu/home-lambdas/issues/10

2022-11-10 09:31 UTC, Jdallos commented on src/apis/schemas/sprint.ts
> +interface Sprint {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:32 UTC, Jdallos commented on src/apis/schemas/task.ts
> +    highPriority: boolean,
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:37 UTC, Jdallos commented on src/apis/schemas/time-entry.ts
> +interface TimeEntry {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:37 UTC, Jdallos commented on src/functions/list-allocations/handler.ts
> +export interface ListAllocationsParameters {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:37 UTC, Jdallos commented on src/functions/list-allocations/handler.ts
> +export interface Response {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:37 UTC, Jdallos commented on src/functions/list-project-sprints/handler.ts
> +export interface ListProjectSprintsParameters {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:38 UTC, Jdallos commented on src/functions/list-project-sprints/handler.ts
> +export interface Response {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:38 UTC, Jdallos commented on src/functions/list-projects/handler.ts
> +export interface ListProjectsParameters {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:39 UTC, Jdallos commented on src/functions/list-tasks/handler.ts
> +export interface Response {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:39 UTC, Jdallos commented on src/functions/list-tasks/handler.ts
> +export interface ListTasksParameters {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:39 UTC, Jdallos commented on src/functions/list-time-entries/handler.ts
> +export interface ListTimeEntriesParameters {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:39 UTC, Jdallos commented on src/functions/list-time-entries/handler.ts
> +export interface Response {
Task created:
https://github.com/Metatavu/home-lambdas/issues/11

2022-11-10 09:43 UTC, Jdallos commented on src/libs/filter-utils.ts
> +export const filterByDate = (object: { start_date: string, end_date: string }, currentDate: Date, parameters: { startDate?: Date, endDate?: Date }): boolean => {
create an interface for the dates to describe their usage e.g. 'DateRange', rather than destructuring

2023-02-27 10:13 UTC, closed without merging